<?php

use Illuminate\Database\Seeder;

class GiphiesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('giphies')->delete();
        
        \DB::table('giphies')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => 'Montaña de mierda',
                'description' => 'A ver que hago con tanto marron',
                'url' => 'https://media.giphy.com/media/R9cQo06nQBpRe/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-11 20:19:40',
                'updated_at' => '2018-12-11 20:19:40',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'title' => 'Pero que coño',
                'description' => 'WTF',
                'url' => 'https://media.giphy.com/media/46yfwmh4XfLKE/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-11 20:20:10',
                'updated_at' => '2018-12-11 20:20:10',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'title' => 'Big Tits 1',
                'description' => 'xxx',
                'url' => 'http://cloud-3.steamusercontent.com/ugc/367407212164140946/47424D0A3E3195834DDC791276EBFDACDCA0D51C/',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:32:55',
                'updated_at' => '2018-12-12 09:32:55',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'title' => 'Big Tits 2',
                'description' => 'xxx',
                'url' => 'http://img.myconfinedspace.com/wp-content/uploads/tdomf-2/511905/bounce-6837-big-tits-bouncingnbsp.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:33:18',
                'updated_at' => '2018-12-12 09:33:18',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'title' => 'Big Tits 3',
                'description' => 'xxx',
                'url' => 'https://s-media-cache-ak0.pinimg.com/originals/cf/85/c7/cf85c7b8113bdd0d9e9afdb345915832.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:33:36',
                'updated_at' => '2018-12-12 09:33:36',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'title' => 'Big Tits 4',
                'description' => 'xxx',
                'url' => 'https://s-media-cache-ak0.pinimg.com/originals/70/f9/9f/70f99fa8c78bf67135a241641b30be80.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:34:03',
                'updated_at' => '2018-12-12 09:34:03',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'title' => 'Big Tits 5',
                'description' => 'xxx',
                'url' => 'http://king-mag.com/files/2015/07/Melanie-Iglesias-GIFs-2.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:34:36',
                'updated_at' => '2018-12-12 09:34:36',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'title' => 'Big Tits 6',
                'description' => 'xxx',
                'url' => 'https://s-media-cache-ak0.pinimg.com/originals/f5/e4/21/f5e421b044e8bbba49278e19ffb5a95e.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:34:56',
                'updated_at' => '2018-12-12 09:34:56',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'title' => 'Alegrar mañana',
                'description' => 'sarita 1',
                'url' => 'https://media.giphy.com/media/zKB8K6gVnMfJe/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:35:29',
                'updated_at' => '2018-12-12 09:35:29',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'title' => 'Alegrar mañana 2',
                'description' => 'sarita 2',
                'url' => 'http://el124.com/wp-content/uploads/2013/06/TaGoHcc.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:35:50',
                'updated_at' => '2018-12-12 09:35:50',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'title' => 'Alegrar mañana 3',
                'description' => 'sarita 3',
                'url' => 'http://i0.wp.com/memecollection.net/wp-content/uploads/2013/12/bikini-girl.gif?fit=270%2C288',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:36:07',
                'updated_at' => '2018-12-12 09:36:07',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'title' => 'Alegrar mañana 4',
                'description' => 'sarita 4',
                'url' => 'http://i25.tinypic.com/23lih08.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:36:27',
                'updated_at' => '2018-12-12 09:36:27',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'title' => 'Feliz mañana',
                'description' => 'xxx',
                'url' => 'http://cdn.ebaumsworld.com/mediaFiles/picture/730195/82875116.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:38:48',
                'updated_at' => '2018-12-12 09:38:48',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'title' => 'American history X',
                'description' => 'bordillo',
                'url' => 'https://68.media.tumblr.com/4bb281403708ef902f3ed37c385c84a6/tumblr_nflav2cclB1r2ljfto1_500.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:39:18',
                'updated_at' => '2018-12-12 09:39:18',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'title' => 'Aplauso 1',
                'description' => 'Citizen Kane aplauso',
                'url' => 'http://www.reactiongifs.us/wp-content/uploads/2013/03/slow_clap_citizen_kane.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:39:49',
                'updated_at' => '2018-12-12 09:40:42',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'title' => 'Aplauso 2',
                'description' => 'Aplauso Dwayne Johnson',
                'url' => 'https://media.giphy.com/media/NnGGHE0muVqpO/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:40:21',
                'updated_at' => '2018-12-12 09:40:21',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'title' => 'Aplauso 3',
                'description' => 'Aplauso Justin Timberlake',
                'url' => 'https://media.giphy.com/media/n5oYbKrHYXylq/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:41:08',
                'updated_at' => '2018-12-12 09:41:08',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'title' => 'Aplauso 4',
                'description' => 'Aplauso Shia Labeouf',
                'url' => 'https://media.giphy.com/media/7rj2ZgttvgomY/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:41:33',
                'updated_at' => '2018-12-12 09:41:33',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'title' => 'Aplauso 4',
                'description' => 'Aplauso Theatre',
                'url' => 'https://media.tenor.co/images/ddc18f037d922238cdb49200e76b5078/raw',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:41:56',
                'updated_at' => '2018-12-12 09:41:56',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'title' => 'Ba dum ts',
                'description' => 'Redoble de tambor',
                'url' => 'http://i.imgur.com/0PfMfYb.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:42:20',
                'updated_at' => '2018-12-12 09:42:20',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'title' => 'Ba dum ts',
                'description' => 'Redoble de tambor',
                'url' => 'http://i.imgur.com/0PfMfYb.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:42:21',
                'updated_at' => '2018-12-12 10:08:34',
                'deleted_at' => '2018-12-12 10:08:34',
            ),
            21 => 
            array (
                'id' => 22,
                'title' => 'Bud Light party',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/R5XMIfn5g7tBK/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:42:47',
                'updated_at' => '2018-12-12 09:42:47',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'title' => 'Cabra lengua',
                'description' => 'la cabra de garcia sacando la lengua',
                'url' => 'http://media1.giphy.com/media/AtlbuhSoW0pJm/200.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:43:19',
                'updated_at' => '2018-12-12 09:43:19',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'title' => 'Cabra mano',
                'description' => 'cabra comiendo de la mano',
                'url' => 'http://media0.giphy.com/media/l304kWweBTkAw/200.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:43:46',
                'updated_at' => '2018-12-12 09:43:46',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'title' => 'Caerse de la silla',
                'description' => '---',
                'url' => 'http://www.reactiongifs.com/r/kllm.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:44:09',
                'updated_at' => '2018-12-12 09:44:09',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'title' => 'Claro que si wapi',
                'description' => 'anuncio tv',
                'url' => 'https://media.giphy.com/media/ai4PXAeSNDU2c/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:44:40',
                'updated_at' => '2018-12-12 09:44:40',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'title' => 'Coincidencia? No lo creo',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/tocDX7CPeYWTC/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:45:15',
                'updated_at' => '2018-12-12 09:45:15',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'title' => 'Comillas Dr. Evil',
                'description' => 'Comillas del Dr. Evil',
                'url' => 'http://www.reactiongifs.com/r/2013/08/air-quotes.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:45:52',
                'updated_at' => '2018-12-12 09:45:52',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'title' => 'Conejo dormido',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/Q42cpzgcUeZkA/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:46:10',
                'updated_at' => '2018-12-12 09:46:10',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'title' => 'Despedida que es viernes',
                'description' => 'Despedida - its-friday',
                'url' => 'http://i.amz.mshcdn.com/EnfWv8QOrKAKvpy5CpUF43qi7YU=/fit-in/850x850/http%3A%2F%2Fmashable.com%2Fwp-content%2Fgallery%2Fthank-gif-its-friday%2Fbye.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:46:49',
                'updated_at' => '2018-12-12 09:46:49',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'title' => 'Mono desesperado con el ordenador',
                'description' => 'makako desesperado',
                'url' => 'http://media4.giphy.com/media/5Zesu5VPNGJlm/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:47:34',
                'updated_at' => '2018-12-12 09:47:34',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'title' => 'Fuck you 1',
                'description' => 'fuck you bucle',
                'url' => 'http://33.media.tumblr.com/tumblr_ltjl1mC95n1qcb3dzo1_500.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:47:59',
                'updated_at' => '2018-12-12 09:47:59',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'title' => 'Fuck you 2',
                'description' => 'fuck you chica',
                'url' => 'https://media.giphy.com/media/7foJXBrUI8mRi/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:48:24',
                'updated_at' => '2018-12-12 09:48:24',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'title' => 'Fuck you 3',
                'description' => 'Fuck you - keyboard Wanted',
                'url' => 'http://i.imgur.com/g2Yo3.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:48:52',
                'updated_at' => '2018-12-12 09:48:52',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'title' => 'Galifianakis',
                'description' => 'Galifianakis - calculating',
                'url' => 'https://media.giphy.com/media/5yLgoceFO3BdJW1zvFu/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:49:12',
                'updated_at' => '2018-12-12 09:49:12',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'title' => 'Georgia Salpa Churro',
                'description' => 'Georgia Salpa - Churro',
                'url' => 'https://media.giphy.com/media/Mkxa4ns8H39Is/giphy-downsized-large.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:49:33',
                'updated_at' => '2018-12-12 09:49:33',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'title' => 'Good morning Wonka',
                'description' => 'gif wonkiano',
                'url' => 'https://media.tenor.co/images/060445d43373cc6106c1d6b1f4cb0f87/tenor.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:49:56',
                'updated_at' => '2018-12-12 09:49:56',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'title' => 'Homer mono platillos',
                'description' => '---',
                'url' => 'http://trv-checkin.s3-eu-central-1.amazonaws.com/wp-content/uploads/sites/12/2015/04/homer-no-piensa-compressor.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:50:17',
                'updated_at' => '2018-12-12 09:50:17',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'title' => 'I Don\'t Know What I\'m Doing',
                'description' => '---',
                'url' => 'http://i.imgur.com/YW3oyA9.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:50:55',
                'updated_at' => '2018-12-12 09:50:55',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'title' => 'In your face',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/l2SpUNb0NN16RadfG/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:51:17',
                'updated_at' => '2018-12-12 09:51:17',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'title' => 'No no no',
                'description' => 'Jack Nicholson - No no no no',
                'url' => 'https://media.giphy.com/media/b8EqUlAFhdy1O/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:51:40',
                'updated_at' => '2018-12-12 09:51:40',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'title' => 'A jugar!!',
                'description' => 'Joaquin Prat - A jugar',
                'url' => 'https://thumbs.gfycat.com/MadeupSimpleCaterpillar-size_restricted.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:54:06',
                'updated_at' => '2018-12-12 09:54:06',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'title' => 'No has dicho la palabra magica',
                'description' => 'Jurassic Park - No has dicho la palabra magica',
                'url' => 'https://media.giphy.com/media/uOAXDA7ZeJJzW/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:54:25',
                'updated_at' => '2018-12-12 09:54:25',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'title' => 'La fuente de la vida',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/yidUzHnBk32Um9aMMw/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:55:18',
                'updated_at' => '2018-12-12 09:55:18',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'title' => 'Ultimos 10 minutos',
                'description' => 'Last 10 minutes',
                'url' => 'http://i.imgur.com/XwjI61v.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:55:41',
                'updated_at' => '2018-12-12 09:55:41',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'title' => 'Magic 1',
                'description' => 'magic',
                'url' => 'http://www.reactiongifs.com/r/mgc.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:56:07',
                'updated_at' => '2018-12-12 09:56:07',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'title' => 'Magic 2',
                'description' => 'magic aritos',
                'url' => 'https://media.giphy.com/media/YVCKFOyDFTnlm/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:56:47',
                'updated_at' => '2018-12-12 09:56:47',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'title' => 'Magic 3',
                'description' => 'magic flores',
                'url' => 'https://media.giphy.com/media/3o7TKP9ln2Dr6ze6f6/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:57:16',
                'updated_at' => '2018-12-12 09:57:16',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'title' => 'Magic 4',
                'description' => 'magic rainbow',
                'url' => 'https://media.giphy.com/media/3o84U6421OOWegpQhq/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:57:36',
                'updated_at' => '2018-12-12 09:57:36',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'title' => 'Monkey Shit',
                'description' => '---',
                'url' => 'http://2.bp.blogspot.com/-JcFxLUHFLM0/TiAK8RIqReI/AAAAAAAAY6Y/uwEHECRW8Pg/s1600/tumblr_lixygvmfsj1qc174to1_400.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:57:59',
                'updated_at' => '2018-12-12 09:57:59',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'title' => 'Mono flipando',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/l0IyaInBwoLwPbWLu/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:58:16',
                'updated_at' => '2018-12-12 09:58:16',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'title' => 'Mono platillos',
                'description' => '---',
                'url' => 'http://www.gifmania.com/Gif-Animados-Objetos/Imagenes-Juguetes/Animales-De-Peluche/Monos-De-Peluche/Mono-Platillos-89234.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:58:35',
                'updated_at' => '2018-12-12 09:58:35',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'title' => 'Nauseas',
                'description' => 'nauseas dos tontos muy tontos',
                'url' => 'https://media.tenor.co/images/73e36a96d7971fdf31ee227a14efbc14/tenor.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:59:05',
                'updated_at' => '2018-12-12 09:59:05',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'title' => 'Ni idea',
                'description' => 'ni idea - house',
                'url' => 'http://31.media.tumblr.com/615cccbfe8ce795a501914bed07f6fc3/tumblr_inline_n02wn5HFOv1rtqugy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 09:59:24',
                'updated_at' => '2018-12-12 09:59:24',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'title' => 'Ni idea 2',
                'description' => 'ni idea -steve martin',
                'url' => 'https://media.giphy.com/media/KWSWC38ifoEZG/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 10:00:04',
                'updated_at' => '2018-12-12 10:00:04',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'title' => 'Niño bailongo',
                'description' => '---',
                'url' => 'https://www.wired.com/images_blogs/underwire/2013/01/crazyfrogbrothers.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 10:00:25',
                'updated_at' => '2018-12-12 10:00:25',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'title' => 'Niño corriendo sorpresa se vuelve',
                'description' => '---',
                'url' => 'http://www.reactiongifs.com/r/nvrmnd.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 10:00:51',
                'updated_at' => '2018-12-12 10:00:51',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'title' => 'Pitbull dale',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/UMi9wrHfvFvTG/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 10:01:12',
                'updated_at' => '2018-12-12 10:01:12',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'title' => 'Please',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/jLKvwWHIXUS4/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 10:01:28',
                'updated_at' => '2018-12-12 10:01:28',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'title' => 'Relax sexy',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/3o7WTyIq1W8FqaWbJu/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 10:01:51',
                'updated_at' => '2018-12-12 10:01:51',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'title' => 'Release the kraken baby',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/E3cQDsj7pUpwI/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 10:02:10',
                'updated_at' => '2018-12-12 10:02:10',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'title' => 'Reloj de arena',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/qMXubVwrW5Gfu/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 10:02:30',
                'updated_at' => '2018-12-12 10:02:30',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'title' => 'Reverencia 1',
                'description' => 'Reverencia - El show de Truman',
                'url' => 'http://media.tumblr.com/740f90580de520b93afdcb2bae632857/tumblr_inline_mnczgqq6jg1qz4rgp.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 10:02:53',
                'updated_at' => '2018-12-12 10:02:53',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'title' => 'Reverencia 2',
                'description' => 'Reverencia - Wayne\'s World',
                'url' => 'http://meyerweb.com/bkkt/not-worthy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 10:03:22',
                'updated_at' => '2018-12-12 10:03:22',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'title' => 'Risa 1',
                'description' => 'risa michael jordan',
                'url' => 'https://media.giphy.com/media/O5NyCibf93upy/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 10:03:42',
                'updated_at' => '2018-12-12 10:03:42',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'title' => 'Risa 2',
                'description' => 'risa shaq oneill',
                'url' => 'https://media.tenor.co/images/0489fb2f025d80cb993ac1e2712682fa/tenor.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 10:04:04',
                'updated_at' => '2018-12-12 10:04:04',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'title' => 'Risa 3',
                'description' => 'Risa - Wolf of Wall Street',
                'url' => 'http://gifrific.com/wp-content/uploads/2014/09/Jordan-Belfort-Fake-Laugh-The-Wolf-of-Wall-Street.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 10:04:21',
                'updated_at' => '2018-12-12 10:04:21',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'title' => 'Sospechoso 1',
                'description' => '---',
                'url' => 'http://vignette1.wikia.nocookie.net/degrassi/images/d/de/Suspicious.gif/revision/latest?cb=20131218221858',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 10:05:16',
                'updated_at' => '2018-12-12 10:05:16',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'title' => 'Tamariz Niana niana nia',
                'description' => 'Niana niana nia',
                'url' => 'https://i.makeagif.com/media/9-18-2014/_eHd87.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 10:05:38',
                'updated_at' => '2018-12-12 10:05:38',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'title' => 'Technoviking 1',
                'description' => '---',
                'url' => 'http://i.imgur.com/6GLasUe.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 10:05:59',
                'updated_at' => '2018-12-12 10:05:59',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'title' => 'The end is near',
                'description' => 'The end is near - Homer',
                'url' => 'https://media.giphy.com/media/dSBCzU9g1WKUU/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 10:07:18',
                'updated_at' => '2018-12-12 10:07:18',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'title' => 'The plan',
                'description' => 'The plan - ogros',
                'url' => 'https://media.giphy.com/media/BHNVC6suWIKs/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 10:07:42',
                'updated_at' => '2018-12-12 10:07:42',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'title' => 'Walking dead',
                'description' => 'The Walking dead - buenooo...',
                'url' => 'http://i.imgur.com/2pbqbhg.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 10:34:48',
                'updated_at' => '2018-12-12 10:34:48',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'title' => 'Walking dead 2',
                'description' => 'The Walking Dead - Happy',
                'url' => 'https://media.giphy.com/media/Aa9zP9nyaHeuY/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 10:35:09',
                'updated_at' => '2018-12-12 10:35:09',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'title' => 'Tom y Jerry',
                'description' => 'Tom y Jerry - ojos celo',
                'url' => 'http://i.amz.mshcdn.com/3UAgTD5T3TCvsE1_dzFPfKBxKbo=/fit-in/850x850/http%3A%2F%2Fmashable.com%2Fwp-content%2Fgallery%2F25-exhuastion-gifs-for-when-you-cant%2Ftired-cat.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 10:35:30',
                'updated_at' => '2018-12-12 10:35:30',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'title' => 'Ultron attack',
                'description' => '---',
                'url' => 'https://cdn2.vox-cdn.com/thumbor/G9YVyGt9q_1slv7mbgIkQO5eTxU=/cdn0.vox-cdn.com/uploads/chorus_asset/file/2928962/2015-01-13_10_39_03.0.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 10:58:32',
                'updated_at' => '2018-12-12 10:58:32',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'title' => 'Ultron look',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/67RCy4sOyixOg/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 10:58:49',
                'updated_at' => '2018-12-12 10:58:49',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'title' => 'Vaso plastico volando',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/11RJe9vIpfGM12/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:00:33',
                'updated_at' => '2018-12-12 11:00:33',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'title' => 'Waynes World 1',
                'description' => 'Waynes World - Excellent',
                'url' => 'https://media.giphy.com/media/8vpeyWA3OWOhG/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:01:06',
                'updated_at' => '2018-12-12 11:01:06',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'title' => 'What is this shit?',
                'description' => 'What is this shit? - Gatos radio',
                'url' => 'http://i.imgur.com/baZaV.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:01:27',
                'updated_at' => '2018-12-12 11:01:27',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'title' => 'Why?',
                'description' => 'why? NBA',
                'url' => 'https://media.giphy.com/media/l4FGqSjdZPAsH39pS/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:01:58',
                'updated_at' => '2018-12-12 11:01:58',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'title' => 'Willie burning',
                'description' => '---',
                'url' => 'https://media.tenor.co/images/6dfe4d605323228c5c9d8d92411104fa/raw',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:02:19',
                'updated_at' => '2018-12-12 11:02:19',
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'title' => 'Willie runing burning',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/w0gjQjNRE9BBu/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:02:40',
                'updated_at' => '2018-12-12 11:02:40',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'title' => 'Arbusto rodando',
                'description' => 'Arbusto del oeste rodando',
                'url' => 'https://media.giphy.com/media/O38dU2kkQ9sWc/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:03:17',
                'updated_at' => '2018-12-12 11:03:17',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'title' => 'Devito y schwache andando 1',
                'description' => '---',
                'url' => 'https://vanessabarneveld.files.wordpress.com/2015/03/76206-schwarzenegger-devito-twins-su-uqkp.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:03:39',
                'updated_at' => '2018-12-12 11:03:39',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'title' => 'Devito y schwache andando 2',
                'description' => '---',
                'url' => 'http://1.bp.blogspot.com/-T_1RnHeN3Fo/UBf2QIuqxAI/AAAAAAAAOms/5JKDpYcruO8/s1600/ARNOLD+SCHWARZENEGGER18.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:03:53',
                'updated_at' => '2018-12-12 11:03:53',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'title' => 'Devito magic',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/13HZaEntj8P22Q/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:04:10',
                'updated_at' => '2018-12-12 11:04:10',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'title' => 'Devito borrachin',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/lv3J6Fm7ZOm5i/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:04:26',
                'updated_at' => '2018-12-12 11:04:26',
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'title' => 'Devito bailongo 1',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/5xaOcLEsWZVbgoVCqbe/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:04:45',
                'updated_at' => '2018-12-12 11:04:45',
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'title' => 'Devito bailongo 2',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/wunLnFC9XA1Dq/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:05:04',
                'updated_at' => '2018-12-12 11:05:04',
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'title' => 'Devito flipando 1',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/3o6Zt2uZ2SO3w87VS0/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:05:24',
                'updated_at' => '2018-12-12 11:05:24',
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'title' => 'Devito flipando 2',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/x8PgVhZD1Wt5S/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:05:41',
                'updated_at' => '2018-12-12 11:05:41',
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'title' => 'Devito saboreando',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/3o7TKH8yWJ4X5iSDMQ/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:06:04',
                'updated_at' => '2018-12-12 11:06:04',
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'title' => 'Devito corte de mangas 1',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/JXjHzVjs8Qv7O/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:06:27',
                'updated_at' => '2018-12-12 11:06:27',
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'title' => 'Devito dice no',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/3o7btT1T9qpQZWhNlK/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:06:41',
                'updated_at' => '2018-12-12 11:06:41',
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'title' => 'Vector caquitas',
                'description' => 'cagada pequeña vectorial',
                'url' => 'http://yunus.hacettepe.edu.tr/~osert/Hotpot_2014_02/02_akdeniz/dolor_de_panza%20-%20Kopya.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:07:07',
                'updated_at' => '2018-12-12 11:07:07',
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'title' => 'Vector cacazas',
                'description' => 'cagada grande vectorial',
                'url' => 'https://ramrock.files.wordpress.com/2014/08/mierda.gif?w=497',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:07:33',
                'updated_at' => '2018-12-12 11:07:33',
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'title' => 'Wonka pirivuelta',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/l0HlHSB8v5yRtBlHW/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:08:02',
                'updated_at' => '2018-12-12 11:08:02',
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'title' => 'Wonka enfadado',
                'description' => '---',
                'url' => 'https://s-media-cache-ak0.pinimg.com/originals/fd/f9/04/fdf9047b2f605e59de67a9047195914a.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:08:22',
                'updated_at' => '2018-12-12 11:08:22',
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'title' => 'Wonka amazing',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/3xz2BPgWgDk4dXvcfm/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:08:44',
                'updated_at' => '2018-12-12 11:08:44',
                'deleted_at' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'title' => 'Wonka alegre',
                'description' => 'Wonka en camison saltando de alegria',
                'url' => 'http://www.disruptiveadvertising.com/wp-content/uploads/2014/08/anigif_enhanced-buzz-15372-1374883539-23.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:09:12',
                'updated_at' => '2018-12-12 11:09:12',
                'deleted_at' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'title' => 'Wonka, cuentanos mas rey moro',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/dVsoSPwNWAEqQ/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:09:38',
                'updated_at' => '2018-12-12 11:09:38',
                'deleted_at' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'title' => 'Montado en wonka',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/aL4pAfh27kBFK/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:10:03',
                'updated_at' => '2018-12-12 11:10:03',
                'deleted_at' => NULL,
            ),
            103 => 
            array (
                'id' => 104,
                'title' => 'Comiendo bombones en la fabrica',
                'description' => '---',
                'url' => 'http://cleverpinkpirate.com/wp-content/uploads/2015/08/tumblr_losx73nJVu1qzydh2o7_250.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:10:27',
                'updated_at' => '2018-12-12 11:10:27',
                'deleted_at' => NULL,
            ),
            104 => 
            array (
                'id' => 105,
                'title' => 'Cactus saltando',
                'description' => '---',
                'url' => 'http://68.media.tumblr.com/2d94c91318ceed1fc4d66aa8538c2751/tumblr_ns4p44Km5t1sjiojbo1_540.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:10:46',
                'updated_at' => '2018-12-12 11:10:46',
                'deleted_at' => NULL,
            ),
            105 => 
            array (
                'id' => 106,
                'title' => 'Chuck puñetazo',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/r0XpwHwR3qiXK/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:11:05',
                'updated_at' => '2018-12-12 11:11:05',
                'deleted_at' => NULL,
            ),
            106 => 
            array (
                'id' => 107,
                'title' => 'Futurama culo en cristal',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/lnXVGJTIy2SdO/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:11:23',
                'updated_at' => '2018-12-12 11:11:23',
                'deleted_at' => NULL,
            ),
            107 => 
            array (
                'id' => 108,
                'title' => 'Sobredosis 1',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/jA2Tr2QT6iMdG/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:11:42',
                'updated_at' => '2018-12-12 11:11:42',
                'deleted_at' => NULL,
            ),
            108 => 
            array (
                'id' => 109,
                'title' => 'Sobredosis 2',
                'description' => '---',
                'url' => 'https://68.media.tumblr.com/1c765a1464d4fc5410442d0dad36ab14/tumblr_ojllwgKlqo1rezg5lo2_500.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:12:03',
                'updated_at' => '2018-12-12 11:12:03',
                'deleted_at' => NULL,
            ),
            109 => 
            array (
                'id' => 110,
                'title' => 'Hanibal lecter 1',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/wQmhVsxVvpVo4/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:12:24',
                'updated_at' => '2018-12-12 11:12:24',
                'deleted_at' => NULL,
            ),
            110 => 
            array (
                'id' => 111,
                'title' => 'Hanibal lecter 2',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/VvTG9RrCeGrza/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:12:43',
                'updated_at' => '2018-12-12 11:12:43',
                'deleted_at' => NULL,
            ),
            111 => 
            array (
                'id' => 112,
                'title' => 'Cara comida por los cerdos',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/qgeA46cLKw1kA/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:13:02',
                'updated_at' => '2018-12-12 11:13:02',
                'deleted_at' => NULL,
            ),
            112 => 
            array (
                'id' => 113,
                'title' => 'Mail chungo',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/l0Iy1U0KU3rBaewjm/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:13:20',
                'updated_at' => '2018-12-12 11:13:20',
                'deleted_at' => NULL,
            ),
            113 => 
            array (
                'id' => 114,
                'title' => 'Programando gato',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/JIX9t2j0ZTN9S/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:13:37',
                'updated_at' => '2018-12-12 11:13:37',
                'deleted_at' => NULL,
            ),
            114 => 
            array (
                'id' => 115,
                'title' => 'Programando rana gustavo',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/XIqCQx02E1U9W/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:14:08',
                'updated_at' => '2018-12-12 11:14:08',
                'deleted_at' => NULL,
            ),
            115 => 
            array (
                'id' => 116,
                'title' => 'Programando carlton banks',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/yUV5CGdRFolKo/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:14:35',
                'updated_at' => '2018-12-12 11:14:35',
                'deleted_at' => NULL,
            ),
            116 => 
            array (
                'id' => 117,
                'title' => 'Ordenador a la basura',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/kHU8W94VS329y/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:14:58',
                'updated_at' => '2018-12-12 11:14:58',
                'deleted_at' => NULL,
            ),
            117 => 
            array (
                'id' => 118,
                'title' => 'Ordenador ardiendo',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/W8FxhUWFqGIQ8/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:15:22',
                'updated_at' => '2018-12-12 11:15:22',
                'deleted_at' => NULL,
            ),
            118 => 
            array (
                'id' => 119,
                'title' => 'Rompiendo ordenador',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/akM24JppWNGeY/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:15:46',
                'updated_at' => '2018-12-12 11:15:46',
                'deleted_at' => NULL,
            ),
            119 => 
            array (
                'id' => 120,
                'title' => 'Ordenador que se revela',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/12FDTkejC4OLaE/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:16:10',
                'updated_at' => '2018-12-12 11:16:10',
                'deleted_at' => NULL,
            ),
            120 => 
            array (
                'id' => 121,
                'title' => 'Ordenador se cae de la terraza',
                'description' => 'a un tonto se le cae el ordenador desde el balcon',
                'url' => 'https://media.giphy.com/media/5zk0hmm3gb6Sc/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:16:40',
                'updated_at' => '2018-12-12 11:16:40',
                'deleted_at' => NULL,
            ),
            121 => 
            array (
                'id' => 122,
                'title' => 'No te dejo copiar codigo',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/VssjBql2ahcE8/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:16:57',
                'updated_at' => '2018-12-12 11:16:57',
                'deleted_at' => NULL,
            ),
            122 => 
            array (
                'id' => 123,
                'title' => 'Rana gustavo al telefono',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/yPhqlJccIOaru/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:17:19',
                'updated_at' => '2018-12-12 11:17:19',
                'deleted_at' => NULL,
            ),
            123 => 
            array (
                'id' => 124,
                'title' => 'Enano a la diana',
                'description' => 'el lobo de wall street',
                'url' => 'http://img.cinemablend.com/cb/5/b/e/0/4/8/5be0485b0bccfdb6223dd203b22a982f7e6f0cf05d8af63de77ae0237e2bccc3.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:17:42',
                'updated_at' => '2018-12-12 11:17:42',
                'deleted_at' => NULL,
            ),
            124 => 
            array (
                'id' => 125,
                'title' => 'Soldados pasando patata caliente',
                'description' => 'se pasan el marron unos a otros',
                'url' => 'http://www.gifsdivertidos.com/wp-content/uploads/2012/07/patata-caliente.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:18:14',
                'updated_at' => '2018-12-12 11:18:14',
                'deleted_at' => NULL,
            ),
            125 => 
            array (
                'id' => 126,
                'title' => 'Oso tocandose los huevos',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/YQCtTI42Fg2xG/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:18:41',
                'updated_at' => '2018-12-12 11:18:41',
                'deleted_at' => NULL,
            ),
            126 => 
            array (
                'id' => 127,
                'title' => 'Despertador con bofetadas',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/gBW8Qgfaa2ije/giphy.gif?response_id=5922e9d12426db9cff3460bc',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:19:06',
                'updated_at' => '2018-12-12 11:19:06',
                'deleted_at' => NULL,
            ),
            127 => 
            array (
                'id' => 128,
                'title' => 'Benny Hill WTF?',
                'description' => 'WTF?',
                'url' => 'https://media.giphy.com/media/hTJg7yWBHiMKs/giphy.gif?response_id=59254f7cec60f22aeb05f4e7',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:19:36',
                'updated_at' => '2018-12-12 11:19:36',
                'deleted_at' => NULL,
            ),
            128 => 
            array (
                'id' => 129,
                'title' => 'Celebracion NBA',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/pgjl0xft8m0iQ/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:19:55',
                'updated_at' => '2018-12-12 11:19:55',
                'deleted_at' => NULL,
            ),
            129 => 
            array (
                'id' => 130,
                'title' => 'Megapoder viento',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/Yr2Qr2MjPX6Ni/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:20:15',
                'updated_at' => '2018-12-12 11:20:15',
                'deleted_at' => NULL,
            ),
            130 => 
            array (
                'id' => 131,
                'title' => 'Eso es todo amigos!!',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/upg0i1m4DLe5q/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:20:36',
                'updated_at' => '2018-12-12 11:20:36',
                'deleted_at' => NULL,
            ),
            131 => 
            array (
                'id' => 132,
                'title' => 'Briatore - Alonso vietnam',
                'description' => '---',
                'url' => 'https://i1.wp.com/cloaca.es/wp-content/uploads/2016/04/Alonso-vietnam.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:21:03',
                'updated_at' => '2018-12-12 11:21:03',
                'deleted_at' => NULL,
            ),
            132 => 
            array (
                'id' => 133,
                'title' => 'Negro de los ruidos',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/mG84Rm8PI2KJi/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:21:22',
                'updated_at' => '2018-12-12 11:21:22',
                'deleted_at' => NULL,
            ),
            133 => 
            array (
                'id' => 134,
                'title' => 'Familia burbuja',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/wx7AhN7zurzHy/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:21:40',
                'updated_at' => '2018-12-12 11:21:40',
                'deleted_at' => NULL,
            ),
            134 => 
            array (
                'id' => 135,
                'title' => 'Familia buble limpiando la burbuja',
                'description' => '---',
                'url' => 'https://media1.tenor.com/images/a00375eb1c82d53d865464b7b9ad39ca/tenor.gif?itemid=5495399',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:22:04',
                'updated_at' => '2018-12-12 11:22:04',
                'deleted_at' => NULL,
            ),
            135 => 
            array (
                'id' => 136,
                'title' => 'Chico buble',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/H9i4qMJIkW772/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:22:27',
                'updated_at' => '2018-12-12 11:22:27',
                'deleted_at' => NULL,
            ),
            136 => 
            array (
                'id' => 137,
                'title' => 'Miraditas',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/3ov9k76MPXVvhGveRG/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:22:41',
                'updated_at' => '2018-12-12 11:22:41',
                'deleted_at' => NULL,
            ),
            137 => 
            array (
                'id' => 138,
                'title' => 'Payaso alegria',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/R66wnaZe2WAvu/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:22:59',
                'updated_at' => '2018-12-12 11:22:59',
                'deleted_at' => NULL,
            ),
            138 => 
            array (
                'id' => 139,
                'title' => 'Payaso preparada',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/SurJgOYLEkN0Y/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:23:16',
                'updated_at' => '2018-12-12 11:23:16',
                'deleted_at' => NULL,
            ),
            139 => 
            array (
                'id' => 140,
                'title' => 'Barrio sesamo',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/xTka01sEV7sFaU3PUY/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:23:31',
                'updated_at' => '2018-12-12 11:23:31',
                'deleted_at' => NULL,
            ),
            140 => 
            array (
                'id' => 141,
                'title' => 'Erase una vez el churro',
                'description' => '---',
                'url' => 'http://i.gyazo.com/07b69d94ff8382355862985d97130f3e.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:23:47',
                'updated_at' => '2018-12-12 11:23:47',
                'deleted_at' => NULL,
            ),
            141 => 
            array (
                'id' => 142,
                'title' => 'Doberman enfadado',
                'description' => '---',
                'url' => 'https://78.media.tumblr.com/ec345b6ce4a284d6ee1b063b4a3309df/tumblr_ohf6oyt6Ri1ufzk7po1_500.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:24:08',
                'updated_at' => '2018-12-12 11:24:08',
                'deleted_at' => NULL,
            ),
            142 => 
            array (
                'id' => 143,
                'title' => 'Churro pedo',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/LFvQBWwKk7Qc0/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:24:23',
                'updated_at' => '2018-12-12 11:24:23',
                'deleted_at' => NULL,
            ),
            143 => 
            array (
                'id' => 144,
                'title' => 'Pedo oso',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/DeAIC76F52wqk/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:24:40',
                'updated_at' => '2018-12-12 11:24:40',
                'deleted_at' => NULL,
            ),
            144 => 
            array (
                'id' => 145,
                'title' => 'Smoker fight',
                'description' => '---',
                'url' => 'https://i.imgur.com/8cLKkVv.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:24:59',
                'updated_at' => '2018-12-12 11:24:59',
                'deleted_at' => NULL,
            ),
            145 => 
            array (
                'id' => 146,
                'title' => 'El fauno original',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/Or7Wxts1AquA0/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:25:19',
                'updated_at' => '2018-12-12 11:25:19',
                'deleted_at' => NULL,
            ),
            146 => 
            array (
                'id' => 147,
                'title' => 'El fauno Mr Burns',
                'description' => '---',
                'url' => 'https://k33.kn3.net/taringa/4/F/4/B/9/8/Popa29/526.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:25:37',
                'updated_at' => '2018-12-12 11:25:37',
                'deleted_at' => NULL,
            ),
            147 => 
            array (
                'id' => 148,
                'title' => 'Barrio sesamo ardiendo',
                'description' => '---',
                'url' => 'https://media1.tenor.com/images/71b3af3541f226215a579fb96386fc35/tenor.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:25:52',
                'updated_at' => '2018-12-12 11:25:52',
                'deleted_at' => NULL,
            ),
            148 => 
            array (
                'id' => 149,
                'title' => 'Apedreamiento',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/9WSSeuJAjYoaA/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:26:07',
                'updated_at' => '2018-12-12 11:26:07',
                'deleted_at' => NULL,
            ),
            149 => 
            array (
                'id' => 150,
                'title' => 'Niño technobaile',
                'description' => '---',
                'url' => 'https://i.gifer.com/7iHz.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:26:26',
                'updated_at' => '2018-12-12 11:26:26',
                'deleted_at' => NULL,
            ),
            150 => 
            array (
                'id' => 151,
                'title' => 'Ralphy llorando',
                'description' => '---',
                'url' => 'https://thumbs.gfycat.com/LastingSphericalAmethystgemclam-small.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:26:45',
                'updated_at' => '2018-12-12 11:26:45',
                'deleted_at' => NULL,
            ),
            151 => 
            array (
                'id' => 152,
                'title' => 'Ralphy saliendo a escondidas',
                'description' => '---',
                'url' => 'https://img.buzzfeed.com/buzzfeed-static/static/2015-12/26/11/enhanced/webdr07/anigif_enhanced-19657-1451146635-7.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:27:04',
                'updated_at' => '2018-12-12 11:27:04',
                'deleted_at' => NULL,
            ),
            152 => 
            array (
                'id' => 153,
                'title' => 'Ralphy programando en arbol',
                'description' => '---',
                'url' => 'https://img.buzzfeed.com/buzzfeed-static/static/2015-12/26/10/enhanced/webdr03/anigif_enhanced-6882-1451142010-3.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:27:24',
                'updated_at' => '2018-12-12 11:27:24',
                'deleted_at' => NULL,
            ),
            153 => 
            array (
                'id' => 154,
                'title' => 'Ralphy expandiendo sabiduria',
                'description' => '---',
                'url' => 'https://img.buzzfeed.com/buzzfeed-static/static/2015-12/26/9/enhanced/webdr08/anigif_enhanced-28800-1451141970-2.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:27:42',
                'updated_at' => '2018-12-12 11:27:42',
                'deleted_at' => NULL,
            ),
            154 => 
            array (
                'id' => 155,
                'title' => 'Ralphy helado en la cabeza',
                'description' => '---',
                'url' => 'https://media1.tenor.com/images/9151cfc59120aa6a3d077510b40188cd/tenor.gif?itemid=10373625',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:28:03',
                'updated_at' => '2018-12-12 11:28:03',
                'deleted_at' => NULL,
            ),
            155 => 
            array (
                'id' => 156,
                'title' => 'Girasoles felices',
                'description' => '---',
                'url' => 'http://www.gifs-animados.es/gifs-imagenes/g/girasoles/gifs-animados-girasoles-584625.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:28:25',
                'updated_at' => '2018-12-12 11:28:25',
                'deleted_at' => NULL,
            ),
            156 => 
            array (
                'id' => 157,
                'title' => 'Peggy en la bañera',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/Hbutx0s2ZYZyw/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:28:42',
                'updated_at' => '2018-12-12 11:28:42',
                'deleted_at' => NULL,
            ),
            157 => 
            array (
                'id' => 158,
                'title' => 'Caida subiendo carretilla de mierda',
                'description' => '---',
                'url' => 'http://25.media.tumblr.com/e68fc8e1d329bf633644c8a912afe4f8/tumblr_mjfvxcrSFt1qbogk6o1_400.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:29:01',
                'updated_at' => '2018-12-12 11:29:01',
                'deleted_at' => NULL,
            ),
            158 => 
            array (
                'id' => 159,
                'title' => 'Travesti comiendo mierda',
                'description' => '---',
                'url' => 'https://i.imgur.com/Uy31Q6a.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:29:21',
                'updated_at' => '2018-12-12 11:29:21',
                'deleted_at' => NULL,
            ),
            159 => 
            array (
                'id' => 160,
                'title' => 'Duo sacapuntas',
                'description' => '---',
                'url' => 'https://thumbs.gfycat.com/HeartyCoolAfricanrockpython-size_restricted.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:29:42',
                'updated_at' => '2018-12-12 11:29:42',
                'deleted_at' => NULL,
            ),
            160 => 
            array (
                'id' => 161,
                'title' => 'Zancadilla gato a niña',
                'description' => '---',
                'url' => 'https://www.srviral.com/contenido/varios/gatoboss.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:30:01',
                'updated_at' => '2018-12-12 11:30:01',
                'deleted_at' => NULL,
            ),
            161 => 
            array (
                'id' => 162,
                'title' => 'Moais hablando',
                'description' => '---',
                'url' => 'https://media1.tenor.com/images/09e206d68aa9fb73c6e13fe35354da46/tenor.gif?itemid=5632533',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:30:22',
                'updated_at' => '2018-12-12 11:30:22',
                'deleted_at' => NULL,
            ),
            162 => 
            array (
                'id' => 163,
                'title' => 'Peggy con gafitas comiendo',
                'description' => '---',
                'url' => 'https://media1.tenor.com/images/cccce9257b9cd55ee8d49d227dcffb58/tenor.gif?itemid=10188743',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:30:48',
                'updated_at' => '2018-12-12 11:30:48',
                'deleted_at' => NULL,
            ),
            163 => 
            array (
                'id' => 164,
                'title' => 'Chupabarbas 1',
                'description' => '---',
                'url' => 'https://i.imgur.com/4aTVwhK.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:31:08',
                'updated_at' => '2018-12-12 11:31:08',
                'deleted_at' => NULL,
            ),
            164 => 
            array (
                'id' => 165,
                'title' => 'Hormiga rodando',
                'description' => '---',
                'url' => 'https://media.giphy.com/media/D0tM2PDdJxMVa/giphy.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:31:26',
                'updated_at' => '2018-12-12 11:31:26',
                'deleted_at' => NULL,
            ),
            165 => 
            array (
                'id' => 166,
                'title' => 'Teniente Down y el recluta patoso',
                'description' => '---',
                'url' => 'https://thumbs.gfycat.com/SentimentalGlaringAmericanwigeon-small.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:31:44',
                'updated_at' => '2018-12-12 11:31:44',
                'deleted_at' => NULL,
            ),
            166 => 
            array (
                'id' => 167,
                'title' => 'Que viene el cron!!!',
                'description' => '---',
                'url' => 'https://ugc.kn3.net/i/origin/http://1.bp.blogspot.com/-dFVLrbAX_EU/Vl01xCNVYzI/AAAAAAAA0_g/bazxnE4kOZ4/s1600/2-10-rotationaldynamics-002.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:32:04',
                'updated_at' => '2018-12-12 11:32:04',
                'deleted_at' => NULL,
            ),
            167 => 
            array (
                'id' => 168,
                'title' => 'Comando pernod en la tanqueta',
                'description' => 'autos locos',
                'url' => 'https://i.pinimg.com/originals/b2/5c/40/b25c4077e8b15c5be6b2010bc4f5f2ad.gif',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:32:25',
                'updated_at' => '2018-12-12 11:32:25',
                'deleted_at' => NULL,
            ),
            168 => 
            array (
                'id' => 169,
                'title' => 'Rana gustavo haciendo calvo',
                'description' => 'imagen',
                'url' => 'http://img.sadistic.pl/pics/a24d678bbd3f.jpg',
                'rating' => 0,
                'copies_number' => 0,
                'created_at' => '2018-12-12 11:32:48',
                'updated_at' => '2018-12-12 11:32:48',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}