FROM php:7.1-apache

RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf

RUN docker-php-ext-install pdo_mysql
RUN apt-get update && \
	apt-get install -y curl && \
	apt-get install -y nano

RUN a2enmod rewrite

ADD . /var/www
ADD ./public /var/www/html

RUN service apache2 restart

#CMD /usr/sbin/apache2ctl -D FOREGROUND